name: Hali

on:
  push:
    # select branch(s)
    branches:
      - master
      - develop
      - test
jobs:
  Test:
    # select the OS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # supported node versions
        node-version: [10.x, 12.x, 13.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g npm yarn
      - run: node --version && npm --version && yarn --version
      - run: yarn && yarn build
      - run: yarn test
